name = "parallelize"
description = "Execute multiple commands in parallel"
version = "0.1.0-dev"

authors = ["Simon Wright"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]
licenses = "Apache-2.0"
website = ""
tags = ["parallel", "execution"]

executables = ["parallelize"]

[build-switches]
"*".contracts = "yes"
"*".ada_version = "ada2022"
